// Generated by CoffeeScript 1.12.3
var Stream, http;

http = require('http');

Stream = require('stream');

module.exports = function() {
  var base;
  http.IncomingMessage.prototype.$json = function(cb) {
    var jsonString;
    jsonString = '';
    this.on('readable', function() {
      var data;
      data = this.read();
      if (data) {
        return jsonString += data.toString();
      }
    });
    return this.on('end', function() {
      return cb(null, JSON.parse(jsonString));
    });
  };
  return (base = http.ServerResponse.prototype).$send || (base.$send = function(err, json) {
    var output;
    this.headers || (this.headers = {});
    if (!this.headers['Content-Type']) {
      this.headers['Content-Type'] = 'application/json';
    }
    if (err) {
      this.writeHead(err.statusCode || 502, this.headers);
      return this.end(JSON.stringify(err));
    }
    if (!json) {
      json = {
        type: 'null'
      };
    }
    if (json.stream) {
      return json.stream.pipe(this);
    } else {
      if (json.data) {
        output = json.data;
      } else {
        output = JSON.stringify(json);
      }
      this.headers['Content-Length'] = output.length;
      this.writeHead(json.statusCode || 200, this.headers);
      this.write(output);
      return this.end();
    }
  });
};
