// Generated by CoffeeScript 1.12.3
var args, command;

command = '';

args = '';

module.exports = {
  match: function(aUrl) {
    var m;
    aUrl = aUrl.replace(/\?.*/, '');
    m = /^\/-\/([^\/]+)\/?(.*)/.exec(aUrl);
    if (m) {
      command = m[1];
      args = m[2].split(/\//);
      return true;
    }
    return false;
  },
  handle: function(req, res) {
    return res.$send(null, [__filename, "handle", command, args]);
  }
};
