// Generated by CoffeeScript 1.12.3
var next, pkg, start,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

pkg = require('../package');

next = function(err) {
  if (err) {
    throw err;
  }
};

start = function(freshen, configFileName) {
  return freshen.readConfig(configFileName, function(err, conf) {
    var server, watcher;
    server = new freshen.Server(conf);
    watcher = new freshen.Watcher(conf, function(data) {
      if (indexOf.call(data.change, configFileName) >= 0) {
        server.stop();
        watcher.stop();
        return start(freshen, configFileName);
      }
      return server.send(JSON.stringify(data));
    });
    freshen.logger.info("Running " + pkg.name + " version " + pkg.version);
    watcher.start(next);
    return server.start(next);
  });
};

module.exports = start;
